name: analytics
description: A new Flutter package for collecting and sending analytical information from the app.
version: 0.1.0
homepage: https://deriv.com/

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  deriv_rudderstack:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_rudderstack
      ref: dev
  firebase_analytics: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
