name: deriv_technical_analysis
description: A Dart package for Technical Analysis.
version: 1.1.2

homepage: https://deriv.com/
repository: https://github.com/deriv-com/flutter-deriv-packages/tree/master/packages/deriv_technical_analysis

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.1"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
