name: deriv_mobile_chart_wrapper
description: A new Flutter package project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.1.9
homepage:

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  deriv_chart:
    git:
      url: git@github.com:regentmarkets/flutter-chart.git
      ref: v0.3.2+2

  deriv_theme:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_theme
      ref: deriv_theme-v2.8.0

  deriv_localizations:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_localizations
      ref: deriv_localizations-v1.7.2

  deriv_ui:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_ui
      ref: deriv_ui-v0.1.2

  provider: ^6.0.5
  flutter_svg: ^2.0.9
  shared_preferences: ^2.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/icons/ic_macd.svg
    - assets/icons/ic_rsi.svg
    - assets/icons/ic_bollinger_bands.svg
    - assets/icons/ic_moving_average.svg
    - assets/icons/ic_indicators_menu.svg
    - assets/icons/ic_indicators_empty_state.svg
    - assets/icons/ic_drawing_tool.svg
    - assets/icons/ic_drawing_tools_empty_state.svg
    - assets/icons/ic_line.svg
    - assets/icons/ic_close_filled.svg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
