name: deriv_rudderstack
description: A new Flutter plugin to wrap RudderStack SDK.
version: 1.1.1

homepage: https://deriv.com/
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: "3.10.2"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.deriv.deriv_rudderstack
        pluginClass: DerivRudderstackPlugin
      ios:
        pluginClass: DerivRudderstackPlugin
