name: example
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"
  flutter: "3.10.2"

dependencies:
  flutter:
    sdk: flutter

  dart_web_socket_handler:
    git:
      url: https://github.com/hamed-deriv/dart_web_socket_handler.git
      ref: main

  flutter_bloc: ^8.1.3
  intl: ^0.18.1
  go_router: ^10.0.0
  shared_preferences: ^2.3.4
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
