name: deriv_auth
description: Provides deriv authentication functionalities for dart/flutter apps.
version: 7.0.4

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: "3.10.2"

publish_to: "none"

dependencies:
  flutter:
    sdk: flutter

  analytics:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/analytics
      ref: analytics-v4.0.0

  deriv_theme:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_theme
      ref: deriv_theme-v2.7.1

  deriv_ui:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_ui
      ref: deriv_ui-v0.1.0+6

  deriv_http_client:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_http_client
      ref: deriv_http_client-v2.0.2

  flutter_deriv_api:
    git:
      url: git@github.com:deriv-com/flutter-deriv-api.git
      ref: v1.3.0

  deriv_web_view:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_web_view
      ref: deriv_web_view-v0.2.2+5

  deriv_localizations:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_localizations
      ref: deriv_localizations-v1.7.0

  deriv_passkeys:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_passkeys
      ref: deriv_passkeys-v0.0.5+8

  deriv_language_selector:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_language_selector
      ref: deriv_language_selector-v0.0.3+13

  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7
  smooth_page_indicator: ^1.1.0
  equatable: ^2.0.5
  package_info_plus: ^8.0.2
  crypto: ^3.0.2
  http: ^0.13.5
  app_links: ^3.4.5

dependency_overrides:
  deriv_ui:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_ui
      ref: deriv_ui-v0.1.0+6

dev_dependencies:
  mocktail: ^1.0.3
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  patrol_finders: ^1.0.0

flutter:
  assets:
    - assets/icons/
    - assets/images/
