name: flutter_deriv_bloc_manager
description: A package based on observer pattern and Service Locator pattern, for managing blocs in Flutter.
version: 0.0.1

homepage: https://deriv.com/
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^8.0.0
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.deriv.app.flutter_deriv_bloc_manager
        pluginClass: FlutterDerivBlocManagerPlugin
      ios:
        pluginClass: FlutterDerivBlocManagerPlugin
