name: deriv_web_view
description: Deriv Web View package project.

version: 0.2.2+5

homepage: https://deriv.com/
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: "3.10.2"

dependencies:
  flutter:
    sdk: flutter

  crypto: ^3.0.2
  equatable: ^2.0.3
  url_launcher: ^6.1.10
  webview_flutter: ^4.2.1
  flutter_inappwebview: ^6.0.0
  flutter_bloc: ^8.1.2
  deriv_http_client:
    git:
      url: https://github.com/deriv-com/flutter-deriv-packages.git
      path: packages/deriv_http_client
      ref: deriv_http_client-v2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
