name: deriv_language_selector
description: A package to select language for the app. It provides both UI and logic for language selection.
version: 0.0.3+15
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  deriv_ui:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_ui
      ref: deriv_ui-v0.1.2
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.6
  mocktail: ^1.0.3

flutter:
  assets:
    - assets/icons/flags/ic_flag_en.png
    - assets/icons/flags/ic_flag_id.png
    - assets/icons/flags/ic_flag_pt.png
    - assets/icons/flags/ic_flag_vi.png
    - assets/icons/flags/ic_flag_zh.png
    - assets/icons/flags/ic_flag_es.png
    - assets/icons/flags/ic_flag_fr.png
    - assets/icons/flags/ic_flag_it.png
    - assets/icons/flags/ic_flag_de.png
    - assets/icons/flags/ic_flag_ru.png
    - assets/icons/flags/ic_flag_th.png
    - assets/icons/flags/ic_flag_pl.png
    - assets/icons/flags/ic_flag_ar.png
    - assets/icons/flags/ic_flag_ko.png
    - assets/icons/flags/ic_flag_sw.png
    - assets/icons/ic_language.svg