name: deriv_numpad
description: A new Flutter project.
version: 1.1.12
publish_to: "none"

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  deriv_theme:
    git:
      url: https://github.com/deriv-com/flutter-deriv-packages.git
      path: packages/deriv_theme
      ref: deriv_theme-v3.0.0

  flutter_svg: ^2.0.7
  intl: ^0.19.0
  decimal: ^2.3.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.0.0

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/ic_handle.svg
    - assets/ic_currency_swap.svg
