name: example
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  deriv_numpad:
    path: ../
  flutter:
    sdk: flutter
  intl: ^0.18.0
  deriv_theme:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_theme
      ref: deriv_theme-v2.2.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/ic_handle.svg
    - assets/ic_currency_swap.svg
