name: deriv_datadog
description: A wrapper around datadog_flutter_plugin to make it easier to use.

version: 0.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: "3.10.2"

dependencies:
  flutter:
    sdk: flutter

  datadog_flutter_plugin: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mocktail: ^0.3.0

flutter:
