name: update_checker
description: Check and retrieve update information from the server for the given package.
version: 3.0.0

homepage: https://deriv.com/
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: "3.10.2"

dependencies:
  bloc: ^8.1.1
  equatable: ^2.0.5
  firebase_database: ^11.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  package_info_plus: ^8.0.2
  firebase_remote_config: ^5.1.2

dev_dependencies:
  bloc_test: ^9.1.1
  mocktail: ^0.3.0
  flutter_test:
    sdk: flutter
  test: ^1.21.4
