name: deriv_http_client
description: A simple HTTP client for Deriv API services.

version: 2.1.0

environment:
  sdk: ">=3.0.0"

dependencies:
  http: ^0.13.4
  flutter_system_proxy:
    git:
      url: https://github.com/BrowserStackCE/flutter_system_proxy.git
      ref: v0.1.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  mocktail: ^1.0.0
