name: deriv_grouped_listview
description: A new Flutter package project.
version: 0.0.2

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: "3.10.2"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
