name: deriv_web_socket_client
description: A package to handle web socket connections this is based on https://github.com/felangel/web_socket_client by Felix Angelov.

version: 1.0.0

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  web_socket_channel: ^2.4.0

dev_dependencies:
  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.21.0
